Drill4J/agent-dotnet

.gitattributes

This forces git to store files internally with normalized line endings. When checking out to the working directory, the line endings will be converted according to the local machine settings. On commit, the endings will be normalized in the git's internal storage.

Provide .gitattributes file to prevent line endings mix

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h

Callback functions are removed from the class and the header and defined `static` in cpp file, also wrapped in anonymous namespace.

Small refactoring of static callbacks

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/ComWrapperBase.h
Drill4dotNet/Drill4dotNet/CorProfilerInfo2.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/FunctionInfo.h
Drill4dotNet/Drill4dotNet/LogBuffer.h
Drill4dotNet/Drill4dotNet/MetaDataImport2.h
Drill4dotNet/Drill4dotNet/OutputUtils.h

Now we have ability to retrieve the Intermediate Language representation of a method being compiled by the CLR machine.
Also includes massive refactoring to make work with COM less painful.

Intermediate Language inspection

---

Drill4dotNet/Drill4dotNet/CorProfilerInfo2.h

Due to wrong mode of closure, the lambda was trying to access a pointer to a destroyed stack frame.
This not appeared on Release, because due to aggressive inlining a stack frame was not created and the final destination was used directly.
If Debug, it started appearing.

Fix Access Violation in CorProfilerCallback2::InitCallable lambda

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/CorProfilerInfo.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/MetaDataImport.h

Preparing to switch to a newer version of interface: renamed own classes, objects, and methods without mentioning specific version of interfaces behind. It would minimize changes in future.

Preparing to switch to a newer version of interface

---

Drill4dotNet/Drill4dotNet/LogBuffer.h
Drill4dotNet/Drill4dotNet/OutputUtils.h

* Fix `LogBuffer` - previously it has not allowed to use stream manipulators, like `std::boolalpha`, `std::hex`, `std::endl`
* Add templates `InBrackets`, `InRoundBrackets`, `InSquareBrackets`, and `InCurlyBrackets` to output the given value surrounded with brackets
* Add similar template `InSpaces` to output the given value surrounded with quote, and `InApostrophes` to surround with single quotes
* Add template `Delimitered` to output the items from the given container with the given delimiter

EPMDJ-2224: Improve output utilities

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CorDataStructures.h
Drill4dotNet/Drill4dotNet/CorProfilerInfo.h

Updated to `ICorProfilerInfo3` to utilize `GetRuntimeInformation`
.NET agent now prints header information: CLR type, runtime version

EPMDJ-2226: .NET agent header information: CLR type, runtime version

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CorProfilerInfo.h
Drill4dotNet/Drill4dotNet/DefineOpCodesGeneratorSpecializations.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/MethodBody.cpp
Drill4dotNet/Drill4dotNet/MethodBody.h
Drill4dotNet/Drill4dotNet/MethodMalloc.h
Drill4dotNet/Drill4dotNet/OpCodes.cpp
Drill4dotNet/Drill4dotNet/OpCodes.h
Drill4dotNet/Drill4dotNet/UnDefineOpCodesGeneratorSpecializations.h
HelloWorld/HelloWorld/Program.cs
HelloWorld/HelloWorldFramework/Program.cs

- Introduce `OpCodes.h` and `OpCodes.cpp` to hold the logic
- Introduce the set of `OpCode_*` classes to represent the possible Intermediate Language instructions
- Introduce `OpCodeVariant`, which can hold one of possible `OpCode_*` classes
- Introduce class `MethodBody`, which parses and compiles back the method header and the stream on instructions
- Introduce methods in COM wrappers, to allow code injection
- Make example injection for method `MyInjectionTarget`
References:
- [ECMA-335, Common Language Infrastructure, part II.25.4 Common Intermediate Language physical layout](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf)
- [Documentation for System.Reflection.Emit](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit?view=netframework-4.8), …

Add ability to inject code into method bodies

---

Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/CorDataStructures.h
Drill4dotNet/Drill4dotNet/CorProfilerInfo.cpp
Drill4dotNet/Drill4dotNet/CorProfilerInfo.h
Drill4dotNet/Drill4dotNet/CoreInteract.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/InfoHandler.cpp
Drill4dotNet/Drill4dotNet/InfoHandler.h
Drill4dotNet/Drill4dotNet/MetaDataImport.h

Part 1. `ICoreInteract` interface
* Introduced `ICoreInteract` interface on `CorProfilerInfo` class;
* Isolated `CProfilerCallback` class from `CorProfilerInfo` class via `ICoreInteract` interface, thus allowing to vary implementation;
* Added isolated concrete implementation of factory-like functions in separate `CorProfileInfo.cpp` file, which can be varied with implementation, for example, in Unit test projects;
* Added implementations of missing pure virtual methods (in pair Get/TryGet) to `CorProfilerInfo` class and corresponding methods to `MetaDataImport` class;
* Hid `MethodMalloc` class usage inside `CorProfilerInfo::SetILFunctionBody`method, which now accepts `vector<byte>` as a new body.
Part 2. Merge `FunctionName` to `FunctionInfo`.
* Merge `FunctionName` structure to …

Refactoring on CorProfilerInfo

---

Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj.filters
Drill4dotNet/Drill4dotNet-Tests/main.cpp
Drill4dotNet/Drill4dotNet-Tests/packages.config
Drill4dotNet/Drill4dotNet-Tests/pch.cpp
Drill4dotNet/Drill4dotNet-Tests/pch.h
README.md

EPMDJ-2381: Update Unit tests to NuGet package `gmock.v1.10.0`
(latest stable) instead `Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1`, since the latter did not include gmock.
Had to define `main()` function and switch off Precompiled Headers on project level because of auto-added files gtest.cc and gmock.cc.

EPMDJ-2381: Update Unit tests to NuGet package `gmock.v1.10.0`

---

Drill4dotNet/Drill4dotNet/ByteUtils.h
Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/ExceptionClause.cpp
Drill4dotNet/Drill4dotNet/ExceptionClause.h
Drill4dotNet/Drill4dotNet/ExceptionsSection.cpp
Drill4dotNet/Drill4dotNet/ExceptionsSection.h
Drill4dotNet/Drill4dotNet/InstructionStream.cpp
Drill4dotNet/Drill4dotNet/InstructionStream.h
Drill4dotNet/Drill4dotNet/MethodBody.cpp
Drill4dotNet/Drill4dotNet/MethodBody.h
Drill4dotNet/Drill4dotNet/MethodHeader.cpp
Drill4dotNet/Drill4dotNet/MethodHeader.h
Drill4dotNet/Drill4dotNet/OpCodes.cpp
Drill4dotNet/Drill4dotNet/OpCodes.h
Drill4dotNet/Drill4dotNet/framework.h
HelloWorld/HelloWorld/Program.cs
HelloWorld/HelloWorldFramework/Program.cs
README.md

Work under EPMDJ-2315.
- Add `noexcept` in several places to fix compiler warnings.
- Introduce `AbsoluteOffset` as a measure for instruction and method body size.
- Extract logic related to method header parsing and serialization from `MethodBody` to `MethodHeader`.
- Introduce `ArgumentConverter` to convert inline arguments from raw bytes to objects.  
Previously, `ConvertArgument` function was doing that.  
`ArgumentConverter` is an upgraded version of the `ConvertArgument` function.  
It looks more like a lambda, and allows to maintain state between parsing subsequent instructions.
- Allow external readonly access to the instructions stream inside the `MethodBody`.
Previously, it was not possible to inject anything into methods with `if`-`else`, loops, and `switch` statements.  
The …

Ability to inject code into methods with branching and try-catches

---

Drill4dotNet/Drill4dotNet-Tests/CProfilerCallbackTest.cpp
Drill4dotNet/Drill4dotNet-Tests/CoreInteractMock.h
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj.filters

* EPMDJ-2348: Mock for `ICoreInteract` interface, Tests for `CProfilerCallback` class using the mock.
It is based on previous commit / pull-request #27.

EPMDJ-2348: Mock for `ICoreInteract` interface and use it

---

Drill4dotNet/Drill4dotNet-Tests/CProfilerCallbackTest.cpp
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj.filters
Drill4dotNet/Drill4dotNet/CDrillProfiler.cpp
Drill4dotNet/Drill4dotNet/CorGUIDs.cpp
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters

EPMDJ-2348: Extracted `#include <corprof_i.cpp>` (required to link IIDs) to common file `CorGUIDs.cpp`.
It is based on #28, essentially has 1 commit.

EPMDJ-2348: Extracted `#include <corprof_i.cpp>` to common file

---

Drill4dotNet/Drill4dotNet-Tests/ByteUtilsTests.cpp
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj.filters
Drill4dotNet/Drill4dotNet-Tests/ExceptionClauseTests.cpp
Drill4dotNet/Drill4dotNet-Tests/ExceptionsSectionTests.cpp
Drill4dotNet/Drill4dotNet-Tests/InstructionStreamTests.cpp
Drill4dotNet/Drill4dotNet-Tests/MethodBodyTests.cpp
Drill4dotNet/Drill4dotNet-Tests/MethodHeaderTests.cpp
Drill4dotNet/Drill4dotNet-Tests/OpCodeVariantTests.cpp

Tests for the main part of work from EPMDJ-2315 , merged as #22 .
- Tests for `MethodHeader`, `ExceptionClause`, and `ExceptionsSection` check how these models of .net entities are parsed and converted back to binary representation.
- Tests for `InstructionStream` check various methods responsible for search in instructions stream and calculation of byte offsets.
- Tests for `MethodBody` check injection into methods with various statements.

Tests for MethodBody and related classes

---

Drill4dotNet/Drill4dotNet-Tests/MethodBodyTests.cpp
Drill4dotNet/Drill4dotNet/MethodBody.cpp

Fixup for EPMDJ-2315.
Previously, the test data was calculated manually, and it specified code size `5` instead of `4`.
Now, the test data is captured from compiler output, and it provides the right value.
The mistake in the test data revealed insufficient error handling in the `MethodBody` constructor.
In `Debug` builds, compiler initializes the newly allocated blocks of memory with pattern like `fd fd fd fd`. There is no such initialization in `Release` builds.
As a result, the `InsertSimpleFunction` was working in `Debug` configuration. The `MethodBody` saw that `CodeSize == 5`, and read values from after the end of the input sequence. Fortunately, because of the memory initialization pattern, the bytes `fd fd` did not correspond to any `OpCode`, and were silently ignored. These 2 …

Fix test data for InsertSimpleFunction test from MethodBodyTests and error handling in MethodBody

---

Drill4dotNet/Drill4dotNet-Tests/ExceptionClauseTests.cpp
Drill4dotNet/Drill4dotNet-Tests/ExceptionsSectionTests.cpp
Drill4dotNet/Drill4dotNet-Tests/InstructionStreamTests.cpp
Drill4dotNet/Drill4dotNet-Tests/MethodBodyTests.cpp
Drill4dotNet/Drill4dotNet-Tests/OpCodeVariantTests.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/MethodBody.cpp
Drill4dotNet/Drill4dotNet/OpCodes.cpp
Drill4dotNet/Drill4dotNet/OpCodes.h

Preparatory stage of work related to EPMDJ-2316 .
Previously, `OpCodes.h` generated a set of free standing `OpCode_CEE_*` classes, each corresponding to a specific Intermediate Language instruction.
These classes had base class `OpCode`.
Now, all these classes are renamed from `OpCode_CEE_*` to `CEE_*`, and wrapped with a class `OpCode`.
The base class is renamed from `OpCode` to `OpCodeArgument` to free name `OpCode` for the wrapping class.
This way, usages of these small classes will look like `OpCode::CEE_NOP`, instead of `OpCode_CEE_NOP`.
The wrapping class allows to put some implementation details of the classes generator into private section.
This will prevent confusing users of `OpCodes.h` with definitions they are not intended to use directly.
Previously, …

OpCode::CEE_* classes now provide information about the stack and flow control behavior

---

Drill4dotNet.sln
Drill4dotNet/Drill4dotNet-Tests/CProfilerCallbackTest.cpp
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet/CProfilerCallback.cpp
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/InfoHandler.cpp
Drill4dotNet/Drill4dotNet/InfoHandler.h
Drill4dotNet/Drill4dotNet/OutputUtils.h
Drill4dotNet/Drill4dotNet/dllmain.cpp
Drill4dotNet/Injection/Injection.csproj
Drill4dotNet/Injection/Program.cs
README.md

EPMDJ-2430: Added Injection.dll stub project.
EPMDJ-2430: Load and get metadata from .NET module `Injection.dll` using IMetaDataDispenser::OpenScope().
EPMDJ-2430: Store Injection metadata in class `InfoHandler`

EPMDJ-2299/EPMDJ-2430: Profiler can load and get metadata from our .NET injection DLL and function

---

Drill4dotNet/Drill4dotNet-Tests/CProfilerCallbackTest.cpp
Drill4dotNet/Drill4dotNet/CDrillProfiler.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/ComInitializer.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/MetaDataDispenser.h
Drill4dotNet/Drill4dotNet/MetaDataImport.h
Drill4dotNet/Drill4dotNet/ProClient.h

Fix issues found after #38 :
- Stop using `MetaDataGetDispenser` function from `rometadata.dll`.
Previously, we were using `MetaDataGetDispenser` function from WinRT API.
This function is not a part of .NET API, and the usage caused a lot of runtime conflicts and issues.
Now, we use `CoCreateInstance` with the required GUIDs directly.
- Fix early disposal of `Connector`: create it directly in `ProClient`.
- Fix array handling in `MetaDataImport::EnumMethodsWithName` and `MetaDataImport::TryEnumMethodsWithName`.
- Fix `GetFunctionInfo` method for `JitCompilationStarted` - wrong Id was used for `GetMethodProps`.

EPMDJ-2299/EPMDJ-2430: Various follow-up fixes

---

Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj
Drill4dotNet/Drill4dotNet-Tests/Drill4dotNet-Tests.vcxproj.filters
Drill4dotNet/Drill4dotNet-Tests/MetadataImportMock.h
Drill4dotNet/Drill4dotNet-Tests/SignatureTests.cpp
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/CorDataStructures.h
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj
Drill4dotNet/Drill4dotNet/Drill4dotNet.vcxproj.filters
Drill4dotNet/Drill4dotNet/IMetadataImport.h
Drill4dotNet/Drill4dotNet/MetaDataImport.h
Drill4dotNet/Drill4dotNet/OutputUtils.h
Drill4dotNet/Drill4dotNet/Signature.cpp
Drill4dotNet/Drill4dotNet/Signature.h

Work under EPMDJ-2316
- Fix `HexOutput` for non-Unicode streams.
- Create `Signature.h` and related files as a place for further changes.
- Parsing binary signature blobs to `MethodSignature`, which also supports serialization back to blob and output to standard streams.
- Update `ICoreInteract` and implementations to retrieve signature blobs of methods.
- Output method signature when decompiling.

Parsing of method signatures

---

Drill4dotNet/Connector/Connector.h
Drill4dotNet/Connector/ConnectorImplementation.h
Drill4dotNet/Connector/main.cpp
Drill4dotNet/Drill4dotNet-Tests/ConnectorMock.h
Drill4dotNet/Drill4dotNet/CDrillProfiler.cpp
Drill4dotNet/Drill4dotNet/CDrillProfiler.h
Drill4dotNet/Drill4dotNet/CProfilerCallback.h
Drill4dotNet/Drill4dotNet/OutputUtils.h
Drill4dotNet/Drill4dotNet/ProClient.h
HelloWorld/Calculator/Calculator.csproj

Work under EPMDJ-2305
Previously, wrong flags were used for `MultiBytToWideChar` function.
As a result, the `DecodeUtf8` function returned empty string.
Now, the right flags are used, and the function is working properly.
This is required to work with Windows applications.
Currently, there is a limitation in the native agent connector - it can only work with console applications.
Until this issue is fixed, the Calculator application will spawn a console.

Allow filtering of assemblies being profiled

---

Drill4dotNet/Connector/Connector.h
Drill4dotNet/Connector/ConnectorImplementation.h
Drill4dotNet/Connector/main.cpp
README.md

Work under EMPDJ-2793
- Refactor conversion from json to data objects related to tree passing
- Introduce HTTP requests to `dispatch-action` for session start and stop
- Handling of session start and stop requests
- Handling of `InitActiveScope`

Send mock coverage data
